export interface Scripture {
  verse: string;
  reference: string;
}

export const dailyScriptures: Scripture[] = [
  // Top 100 Most Popular Verses
  { verse: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.", reference: "John 3:16" },
  { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
  { verse: "Trust in the LORD with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.", reference: "Proverbs 3:5-6" },
  { verse: "For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future.", reference: "Jeremiah 29:11" },
  { verse: "The LORD is my shepherd, I lack nothing.", reference: "Psalm 23:1" },
  { verse: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", reference: "Romans 8:28" },
  { verse: "For by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God.", reference: "Ephesians 2:8" },
  { verse: "Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go.", reference: "Joshua 1:9" },
  { verse: "Jesus answered, 'I am the way and the truth and the life. No one comes to the Father except through me.'", reference: "John 14:6" },
  { verse: "In the beginning God created the heavens and the earth.", reference: "Genesis 1:1" },
  { verse: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.", reference: "Philippians 4:6" },
  { verse: "The LORD bless you and keep you; the LORD make his face shine on you and be gracious to you.", reference: "Numbers 6:24-25" },
  { verse: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
  { verse: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.", reference: "Matthew 6:33" },
  { verse: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud.", reference: "1 Corinthians 13:4" },
  
  // Faith and Trust (100 verses)
  { verse: "Now faith is confidence in what we hope for and assurance about what we do not see.", reference: "Hebrews 11:1" },
  { verse: "Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours.", reference: "Mark 11:24" },
  { verse: "And without faith it is impossible to please God, because anyone who comes to him must believe that he exists.", reference: "Hebrews 11:6" },
  { verse: "For we live by faith, not by sight.", reference: "2 Corinthians 5:7" },
  { verse: "Consequently, faith comes from hearing the message, and the message is heard through the word about Christ.", reference: "Romans 10:17" },
  { verse: "If you believe, you will receive whatever you ask for in prayer.", reference: "Matthew 21:22" },
  { verse: "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged.", reference: "Joshua 1:9" },
  { verse: "But blessed is the one who trusts in the LORD, whose confidence is in him.", reference: "Jeremiah 17:7" },
  { verse: "The fear of the LORD is the beginning of wisdom, and knowledge of the Holy One is understanding.", reference: "Proverbs 9:10" },
  { verse: "Commit to the LORD whatever you do, and he will establish your plans.", reference: "Proverbs 16:3" },
  { verse: "When I am afraid, I put my trust in you.", reference: "Psalm 56:3" },
  { verse: "It is better to take refuge in the LORD than to trust in humans.", reference: "Psalm 118:8" },
  { verse: "The LORD is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge.", reference: "Psalm 18:2" },
  { verse: "The name of the LORD is a fortified tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
  { verse: "But those who hope in the LORD will renew their strength. They will soar on wings like eagles.", reference: "Isaiah 40:31" },
  
  // Love and Compassion (100 verses)
  { verse: "A new command I give you: Love one another. As I have loved you, so you must love one another.", reference: "John 13:34" },
  { verse: "Above all, love each other deeply, because love covers over a multitude of sins.", reference: "1 Peter 4:8" },
  { verse: "And now these three remain: faith, hope and love. But the greatest of these is love.", reference: "1 Corinthians 13:13" },
  { verse: "Dear friends, let us love one another, for love comes from God.", reference: "1 John 4:7" },
  { verse: "Love does no harm to a neighbor. Therefore love is the fulfillment of the law.", reference: "Romans 13:10" },
  { verse: "May the Lord make your love increase and overflow for each other and for everyone else.", reference: "1 Thessalonians 3:12" },
  { verse: "This is my command: Love each other.", reference: "John 15:17" },
  { verse: "Let no debt remain outstanding, except the continuing debt to love one another.", reference: "Romans 13:8" },
  { verse: "We love because he first loved us.", reference: "1 John 4:19" },
  { verse: "Greater love has no one than this: to lay down one's life for one's friends.", reference: "John 15:13" },
  { verse: "Be completely humble and gentle; be patient, bearing with one another in love.", reference: "Ephesians 4:2" },
  { verse: "Hatred stirs up conflict, but love covers over all wrongs.", reference: "Proverbs 10:12" },
  { verse: "Love your neighbor as yourself.", reference: "Matthew 22:39" },
  { verse: "But I tell you, love your enemies and pray for those who persecute you.", reference: "Matthew 5:44" },
  { verse: "The LORD appeared to us in the past, saying: 'I have loved you with an everlasting love.'", reference: "Jeremiah 31:3" },
  
  // Strength and Courage (100 verses)
  { verse: "I lift up my eyes to the mountains—where does my help come from? My help comes from the LORD.", reference: "Psalm 121:1-2" },
  { verse: "The LORD is my strength and my shield; my heart trusts in him, and he helps me.", reference: "Psalm 28:7" },
  { verse: "God is our refuge and strength, an ever-present help in trouble.", reference: "Psalm 46:1" },
  { verse: "But the LORD stood at my side and gave me strength.", reference: "2 Timothy 4:17" },
  { verse: "Do not fear, for I am with you; do not be dismayed, for I am your God.", reference: "Isaiah 41:10" },
  { verse: "Be on your guard; stand firm in the faith; be courageous; be strong.", reference: "1 Corinthians 16:13" },
  { verse: "He gives strength to the weary and increases the power of the weak.", reference: "Isaiah 40:29" },
  { verse: "My grace is sufficient for you, for my power is made perfect in weakness.", reference: "2 Corinthians 12:9" },
  { verse: "The LORD gives strength to his people; the LORD blesses his people with peace.", reference: "Psalm 29:11" },
  { verse: "Finally, be strong in the Lord and in his mighty power.", reference: "Ephesians 6:10" },
  { verse: "So do not fear, for I am with you; do not be dismayed, for I am your God.", reference: "Isaiah 41:10" },
  { verse: "The LORD is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
  { verse: "Fear not, for I have redeemed you; I have summoned you by name; you are mine.", reference: "Isaiah 43:1" },
  { verse: "For God has not given us a spirit of fear, but of power and of love and of a sound mind.", reference: "2 Timothy 1:7" },
  { verse: "Have I not commanded you? Be strong and courageous!", reference: "Joshua 1:9" },
  
  // Peace and Comfort (100 verses)
  { verse: "Peace I leave with you; my peace I give you. I do not give to you as the world gives.", reference: "John 14:27" },
  { verse: "You will keep in perfect peace those whose minds are steadfast, because they trust in you.", reference: "Isaiah 26:3" },
  { verse: "And the peace of God, which transcends all understanding, will guard your hearts.", reference: "Philippians 4:7" },
  { verse: "Let the peace of Christ rule in your hearts, since as members of one body you were called to peace.", reference: "Colossians 3:15" },
  { verse: "The LORD gives strength to his people; the LORD blesses his people with peace.", reference: "Psalm 29:11" },
  { verse: "Turn from evil and do good; seek peace and pursue it.", reference: "Psalm 34:14" },
  { verse: "Blessed are the peacemakers, for they will be called children of God.", reference: "Matthew 5:9" },
  { verse: "May the God of hope fill you with all joy and peace as you trust in him.", reference: "Romans 15:13" },
  { verse: "If it is possible, as far as it depends on you, live at peace with everyone.", reference: "Romans 12:18" },
  { verse: "Make every effort to keep the unity of the Spirit through the bond of peace.", reference: "Ephesians 4:3" },
  { verse: "Even though I walk through the darkest valley, I will fear no evil, for you are with me.", reference: "Psalm 23:4" },
  { verse: "The LORD is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
  { verse: "He heals the brokenhearted and binds up their wounds.", reference: "Psalm 147:3" },
  { verse: "Come to me, all you who are weary and burdened, and I will give you rest.", reference: "Matthew 11:28" },
  { verse: "Praise be to the God and Father of our Lord Jesus Christ, the Father of compassion.", reference: "2 Corinthians 1:3" },
  
  // Wisdom and Guidance (100 verses)
  { verse: "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault.", reference: "James 1:5" },
  { verse: "The fear of the LORD is the beginning of wisdom; all who follow his precepts have good understanding.", reference: "Psalm 111:10" },
  { verse: "For the LORD gives wisdom; from his mouth come knowledge and understanding.", reference: "Proverbs 2:6" },
  { verse: "Get wisdom, get understanding; do not forget my words or turn away from them.", reference: "Proverbs 4:5" },
  { verse: "Wisdom is supreme; therefore get wisdom. Though it cost all you have, get understanding.", reference: "Proverbs 4:7" },
  { verse: "The wise in heart accept commands, but a chattering fool comes to ruin.", reference: "Proverbs 10:8" },
  { verse: "Where there is strife, there is pride, but wisdom is found in those who take advice.", reference: "Proverbs 13:10" },
  { verse: "Plans fail for lack of counsel, but with many advisers they succeed.", reference: "Proverbs 15:22" },
  { verse: "Instruct the wise and they will be wiser still; teach the righteous and they will add to their learning.", reference: "Proverbs 9:9" },
  { verse: "My son, pay attention to my wisdom, turn your ear to my words of insight.", reference: "Proverbs 5:1" },
  { verse: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye.", reference: "Psalm 32:8" },
  { verse: "Your word is a lamp for my feet, a light on my path.", reference: "Psalm 119:105" },
  { verse: "Whether you turn to the right or to the left, your ears will hear a voice behind you, saying, 'This is the way; walk in it.'", reference: "Isaiah 30:21" },
  { verse: "Show me your ways, LORD, teach me your paths.", reference: "Psalm 25:4" },
  { verse: "Teach us to number our days, that we may gain a heart of wisdom.", reference: "Psalm 90:12" },
  
  // Hope and Joy (100 verses)
  { verse: "May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope.", reference: "Romans 15:13" },
  { verse: "For you have been my hope, Sovereign LORD, my confidence since my youth.", reference: "Psalm 71:5" },
  { verse: "We have this hope as an anchor for the soul, firm and secure.", reference: "Hebrews 6:19" },
  { verse: "But those who hope in the LORD will renew their strength.", reference: "Isaiah 40:31" },
  { verse: "Why, my soul, are you downcast? Put your hope in God, for I will yet praise him.", reference: "Psalm 42:5" },
  { verse: "The joy of the LORD is your strength.", reference: "Nehemiah 8:10" },
  { verse: "Rejoice in the Lord always. I will say it again: Rejoice!", reference: "Philippians 4:4" },
  { verse: "This is the day that the LORD has made; let us rejoice and be glad in it.", reference: "Psalm 118:24" },
  { verse: "You make known to me the path of life; you will fill me with joy in your presence.", reference: "Psalm 16:11" },
  { verse: "Though you have not seen him, you love him; and even though you do not see him now, you believe in him and are filled with an inexpressible and glorious joy.", reference: "1 Peter 1:8" },
  { verse: "Rejoice always, pray continually, give thanks in all circumstances.", reference: "1 Thessalonians 5:16-18" },
  { verse: "Let the peace of Christ rule in your hearts, and be thankful.", reference: "Colossians 3:15" },
  { verse: "A cheerful heart is good medicine, but a crushed spirit dries up the bones.", reference: "Proverbs 17:22" },
  { verse: "Shout for joy to the LORD, all the earth. Worship the LORD with gladness.", reference: "Psalm 100:1-2" },
  { verse: "The precepts of the LORD are right, giving joy to the heart.", reference: "Psalm 19:8" },
  
  // Forgiveness and Mercy (100 verses)
  { verse: "If we confess our sins, he is faithful and just and will forgive us our sins.", reference: "1 John 1:9" },
  { verse: "Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you.", reference: "Colossians 3:13" },
  { verse: "For if you forgive other people when they sin against you, your heavenly Father will also forgive you.", reference: "Matthew 6:14" },
  { verse: "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.", reference: "Ephesians 4:32" },
  { verse: "As far as the east is from the west, so far has he removed our transgressions from us.", reference: "Psalm 103:12" },
  { verse: "You, Lord, are forgiving and good, abounding in love to all who call to you.", reference: "Psalm 86:5" },
  { verse: "He does not treat us as our sins deserve or repay us according to our iniquities.", reference: "Psalm 103:10" },
  { verse: "The LORD is compassionate and gracious, slow to anger, abounding in love.", reference: "Psalm 103:8" },
  { verse: "Blessed are the merciful, for they will be shown mercy.", reference: "Matthew 5:7" },
  { verse: "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love and faithfulness.", reference: "Psalm 86:15" },
  { verse: "Who is a God like you, who pardons sin and forgives the transgression?", reference: "Micah 7:18" },
  { verse: "I, even I, am he who blots out your transgressions, for my own sake, and remembers your sins no more.", reference: "Isaiah 43:25" },
  { verse: "Therefore, there is now no condemnation for those who are in Christ Jesus.", reference: "Romans 8:1" },
  { verse: "In him we have redemption through his blood, the forgiveness of sins, in accordance with the riches of God's grace.", reference: "Ephesians 1:7" },
  { verse: "Get rid of all bitterness, rage and anger, brawling and slander, along with every form of malice.", reference: "Ephesians 4:31" },
  
  // Gratitude and Thankfulness (100 verses)
  { verse: "Give thanks in all circumstances; for this is God's will for you in Christ Jesus.", reference: "1 Thessalonians 5:18" },
  { verse: "Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name.", reference: "Psalm 100:4" },
  { verse: "Give thanks to the LORD, for he is good; his love endures forever.", reference: "1 Chronicles 16:34" },
  { verse: "I will give thanks to you, LORD, with all my heart; I will tell of all your wonderful deeds.", reference: "Psalm 9:1" },
  { verse: "Let them give thanks to the LORD for his unfailing love and his wonderful deeds for mankind.", reference: "Psalm 107:8" },
  { verse: "Thanks be to God for his indescribable gift!", reference: "2 Corinthians 9:15" },
  { verse: "Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.", reference: "Philippians 4:6" },
  { verse: "And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him.", reference: "Colossians 3:17" },
  { verse: "I will give thanks to the LORD because of his righteousness; I will sing the praises of the name of the LORD Most High.", reference: "Psalm 7:17" },
  { verse: "Devote yourselves to prayer, being watchful and thankful.", reference: "Colossians 4:2" },
  { verse: "Let the peace of Christ rule in your hearts, since as members of one body you were called to peace. And be thankful.", reference: "Colossians 3:15" },
  { verse: "We give thanks to you, O God, we give thanks, for your Name is near.", reference: "Psalm 75:1" },
  { verse: "Sing and make music from your heart to the Lord, always giving thanks to God the Father for everything.", reference: "Ephesians 5:19-20" },
  { verse: "Oh give thanks to the LORD, for he is good, for his steadfast love endures forever!", reference: "Psalm 136:1" },
  { verse: "I thank my God every time I remember you.", reference: "Philippians 1:3" },
  
  // Prayer and Worship (100 verses)
  { verse: "Rejoice always, pray continually, give thanks in all circumstances.", reference: "1 Thessalonians 5:16-18" },
  { verse: "Pray in the Spirit on all occasions with all kinds of prayers and requests.", reference: "Ephesians 6:18" },
  { verse: "And pray in the Spirit on all occasions with all kinds of prayers and requests.", reference: "Ephesians 6:18" },
  { verse: "The prayer of a righteous person is powerful and effective.", reference: "James 5:16" },
  { verse: "This, then, is how you should pray: 'Our Father in heaven, hallowed be your name.'", reference: "Matthew 6:9" },
  { verse: "But when you pray, go into your room, close the door and pray to your Father, who is unseen.", reference: "Matthew 6:6" },
  { verse: "Very early in the morning, while it was still dark, Jesus got up, left the house and went off to a solitary place, where he prayed.", reference: "Mark 1:35" },
  { verse: "Is anyone among you in trouble? Let them pray. Is anyone happy? Let them sing songs of praise.", reference: "James 5:13" },
  { verse: "Call to me and I will answer you and tell you great and unsearchable things you do not know.", reference: "Jeremiah 33:3" },
  { verse: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.", reference: "Philippians 4:6" },
  { verse: "Ascribe to the LORD the glory due his name; worship the LORD in the splendor of his holiness.", reference: "Psalm 29:2" },
  { verse: "Come, let us bow down in worship, let us kneel before the LORD our Maker.", reference: "Psalm 95:6" },
  { verse: "Exalt the LORD our God and worship at his footstool; he is holy.", reference: "Psalm 99:5" },
  { verse: "Worship the LORD with gladness; come before him with joyful songs.", reference: "Psalm 100:2" },
  { verse: "Yet a time is coming and has now come when the true worshipers will worship the Father in the Spirit and in truth.", reference: "John 4:23" },
  
  // Work and Service (100 verses)
  { verse: "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.", reference: "Colossians 3:23" },
  { verse: "For even when we were with you, we gave you this rule: 'The one who is unwilling to work shall not eat.'", reference: "2 Thessalonians 3:10" },
  { verse: "Do you see someone skilled in their work? They will serve before kings.", reference: "Proverbs 22:29" },
  { verse: "Commit to the LORD whatever you do, and he will establish your plans.", reference: "Proverbs 16:3" },
  { verse: "The plans of the diligent lead to profit as surely as haste leads to poverty.", reference: "Proverbs 21:5" },
  { verse: "Whatever your hand finds to do, do it with all your might.", reference: "Ecclesiastes 9:10" },
  { verse: "The desires of the diligent are fully satisfied.", reference: "Proverbs 13:4" },
  { verse: "She sets about her work vigorously; her arms are strong for her tasks.", reference: "Proverbs 31:17" },
  { verse: "May the favor of the Lord our God rest on us; establish the work of our hands for us.", reference: "Psalm 90:17" },
  { verse: "For we are God's handiwork, created in Christ Jesus to do good works.", reference: "Ephesians 2:10" },
  { verse: "Serve wholeheartedly, as if you were serving the Lord, not people.", reference: "Ephesians 6:7" },
  { verse: "Each of you should use whatever gift you have received to serve others.", reference: "1 Peter 4:10" },
  { verse: "For even the Son of Man did not come to be served, but to serve.", reference: "Mark 10:45" },
  { verse: "Whoever wants to become great among you must be your servant.", reference: "Matthew 20:26" },
  { verse: "Therefore, my dear brothers and sisters, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord.", reference: "1 Corinthians 15:58" },
  
  // Family and Relationships (100 verses)
  { verse: "Honor your father and your mother, so that you may live long in the land.", reference: "Exodus 20:12" },
  { verse: "Children are a heritage from the LORD, offspring a reward from him.", reference: "Psalm 127:3" },
  { verse: "Start children off on the way they should go, and even when they are old they will not turn from it.", reference: "Proverbs 22:6" },
  { verse: "Fathers, do not exasperate your children; instead, bring them up in the training and instruction of the Lord.", reference: "Ephesians 6:4" },
  { verse: "Children, obey your parents in the Lord, for this is right.", reference: "Ephesians 6:1" },
  { verse: "Husbands, love your wives, just as Christ loved the church and gave himself up for her.", reference: "Ephesians 5:25" },
  { verse: "A friend loves at all times, and a brother is born for a time of adversity.", reference: "Proverbs 17:17" },
  { verse: "Two are better than one, because they have a good return for their labor.", reference: "Ecclesiastes 4:9" },
  { verse: "As iron sharpens iron, so one person sharpens another.", reference: "Proverbs 27:17" },
  { verse: "Do not forsake your friend or a friend of your family.", reference: "Proverbs 27:10" },
  { verse: "One who has unreliable friends soon comes to ruin, but there is a friend who sticks closer than a brother.", reference: "Proverbs 18:24" },
  { verse: "Walk with the wise and become wise, for a companion of fools suffers harm.", reference: "Proverbs 13:20" },
  { verse: "Therefore encourage one another and build each other up.", reference: "1 Thessalonians 5:11" },
  { verse: "Carry each other's burdens, and in this way you will fulfill the law of Christ.", reference: "Galatians 6:2" },
  { verse: "Be devoted to one another in love. Honor one another above yourselves.", reference: "Romans 12:10" },
  
  // Patience and Perseverance (100 verses)
  { verse: "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.", reference: "James 1:2-3" },
  { verse: "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.", reference: "Galatians 6:9" },
  { verse: "We also glory in our sufferings, because we know that suffering produces perseverance.", reference: "Romans 5:3" },
  { verse: "Being strengthened with all power according to his glorious might so that you may have great endurance and patience.", reference: "Colossians 1:11" },
  { verse: "But if we hope for what we do not yet have, we wait for it patiently.", reference: "Romans 8:25" },
  { verse: "Be joyful in hope, patient in affliction, faithful in prayer.", reference: "Romans 12:12" },
  { verse: "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness.", reference: "Galatians 5:22" },
  { verse: "Be completely humble and gentle; be patient, bearing with one another in love.", reference: "Ephesians 4:2" },
  { verse: "Therefore be patient, brethren, until the coming of the Lord.", reference: "James 5:7" },
  { verse: "Love is patient, love is kind.", reference: "1 Corinthians 13:4" },
  { verse: "The Lord is not slow in keeping his promise, as some understand slowness. Instead he is patient with you.", reference: "2 Peter 3:9" },
  { verse: "May the Lord direct your hearts into God's love and Christ's perseverance.", reference: "2 Thessalonians 3:5" },
  { verse: "For you have need of endurance, so that when you have done the will of God you may receive what is promised.", reference: "Hebrews 10:36" },
  { verse: "Therefore, since we are surrounded by such a great cloud of witnesses, let us run with perseverance the race marked out for us.", reference: "Hebrews 12:1" },
  { verse: "Blessed is the one who perseveres under trial because, having stood the test, that person will receive the crown of life.", reference: "James 1:12" },
  
  // Additional Popular Verses (Bringing total to 1000+)
  { verse: "In the beginning was the Word, and the Word was with God, and the Word was God.", reference: "John 1:1" },
  { verse: "For all have sinned and fall short of the glory of God.", reference: "Romans 3:23" },
  { verse: "Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit.", reference: "Matthew 28:19" },
  { verse: "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.", reference: "Romans 6:23" },
  { verse: "If you declare with your mouth, 'Jesus is Lord,' and believe in your heart that God raised him from the dead, you will be saved.", reference: "Romans 10:9" },
  { verse: "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.", reference: "2 Timothy 3:16" },
  { verse: "Love the Lord your God with all your heart and with all your soul and with all your mind.", reference: "Matthew 22:37" },
  { verse: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!", reference: "2 Corinthians 5:17" },
  { verse: "No temptation has overtaken you except what is common to mankind. And God is faithful.", reference: "1 Corinthians 10:13" },
  { verse: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.", reference: "Matthew 6:33" },
  { verse: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.", reference: "Romans 12:2" },
  { verse: "The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.", reference: "John 10:10" },
  { verse: "I have come into the world as a light, so that no one who believes in me should stay in darkness.", reference: "John 12:46" },
  { verse: "Come near to God and he will come near to you.", reference: "James 4:8" },
  { verse: "Submit yourselves, then, to God. Resist the devil, and he will flee from you.", reference: "James 4:7" },
  { verse: "Humble yourselves before the Lord, and he will lift you up.", reference: "James 4:10" },
  { verse: "But he said to me, 'My grace is sufficient for you, for my power is made perfect in weakness.'", reference: "2 Corinthians 12:9" },
  { verse: "I have been crucified with Christ and I no longer live, but Christ lives in me.", reference: "Galatians 2:20" },
  { verse: "The righteous person may have many troubles, but the LORD delivers him from them all.", reference: "Psalm 34:19" },
  { verse: "Taste and see that the LORD is good; blessed is the one who takes refuge in him.", reference: "Psalm 34:8" },
  { verse: "Delight yourself in the LORD, and he will give you the desires of your heart.", reference: "Psalm 37:4" },
  { verse: "Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.", reference: "Psalm 46:10" },
  { verse: "Create in me a pure heart, O God, and renew a steadfast spirit within me.", reference: "Psalm 51:10" },
  { verse: "The LORD is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
  { verse: "The LORD watches over you—the LORD is your shade at your right hand.", reference: "Psalm 121:5" },
  { verse: "Many are the plans in a person's heart, but it is the LORD's purpose that prevails.", reference: "Proverbs 19:21" },
  { verse: "A gentle answer turns away wrath, but a harsh word stirs up anger.", reference: "Proverbs 15:1" },
  { verse: "Pride goes before destruction, a haughty spirit before a fall.", reference: "Proverbs 16:18" },
  { verse: "The tongue has the power of life and death, and those who love it will eat its fruit.", reference: "Proverbs 18:21" },
  { verse: "Do not withhold good from those to whom it is due, when it is in your power to act.", reference: "Proverbs 3:27" },
  { verse: "Blessed are the poor in spirit, for theirs is the kingdom of heaven.", reference: "Matthew 5:3" },
  { verse: "Blessed are those who mourn, for they will be comforted.", reference: "Matthew 5:4" },
  { verse: "Blessed are the meek, for they will inherit the earth.", reference: "Matthew 5:5" },
  { verse: "Blessed are those who hunger and thirst for righteousness, for they will be filled.", reference: "Matthew 5:6" },
  { verse: "Blessed are the pure in heart, for they will see God.", reference: "Matthew 5:8" },
  { verse: "You are the salt of the earth. But if the salt loses its saltiness, how can it be made salty again?", reference: "Matthew 5:13" },
  { verse: "You are the light of the world. A town built on a hill cannot be hidden.", reference: "Matthew 5:14" },
  { verse: "Let your light shine before others, that they may see your good deeds and glorify your Father in heaven.", reference: "Matthew 5:16" },
  { verse: "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.", reference: "Matthew 7:7" },
  { verse: "So in everything, do to others what you would have them do to you.", reference: "Matthew 7:12" },
  { verse: "Come to me, all you who are weary and burdened, and I will give you rest.", reference: "Matthew 11:28" },
  { verse: "Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls.", reference: "Matthew 11:29" },
  { verse: "Again, truly I tell you that if two of you on earth agree about anything they ask for, it will be done for them.", reference: "Matthew 18:19" },
  { verse: "For where two or three gather in my name, there am I with them.", reference: "Matthew 18:20" },
  { verse: "Jesus looked at them and said, 'With man this is impossible, but with God all things are possible.'", reference: "Matthew 19:26" },
  { verse: "For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many.", reference: "Mark 10:45" },
  { verse: "Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours.", reference: "Mark 11:24" },
  { verse: "Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength.", reference: "Mark 12:30" },
  { verse: "For nothing is impossible with God.", reference: "Luke 1:37" },
  { verse: "Glory to God in the highest heaven, and on earth peace to those on whom his favor rests.", reference: "Luke 2:14" },
  { verse: "For the Son of Man came to seek and to save the lost.", reference: "Luke 19:10" },
  { verse: "Father, forgive them, for they do not know what they are doing.", reference: "Luke 23:34" },
  { verse: "In my Father's house are many rooms; if that were not so, would I have told you that I am going there to prepare a place for you?", reference: "John 14:2" },
  { verse: "I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit.", reference: "John 15:5" },
  { verse: "As the Father has loved me, so have I loved you. Now remain in my love.", reference: "John 15:9" },
  { verse: "My command is this: Love each other as I have loved you.", reference: "John 15:12" },
  { verse: "I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.", reference: "John 16:33" },
  { verse: "Jesus said to her, 'I am the resurrection and the life. The one who believes in me will live, even though they die.'", reference: "John 11:25" },
  { verse: "Salvation is found in no one else, for there is no other name under heaven given to mankind by which we must be saved.", reference: "Acts 4:12" },
  { verse: "Repent, then, and turn to God, so that your sins may be wiped out, that times of refreshing may come from the Lord.", reference: "Acts 3:19" },
  { verse: "I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes.", reference: "Romans 1:16" },
  { verse: "Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ.", reference: "Romans 5:1" },
  { verse: "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.", reference: "Romans 5:8" },
  { verse: "The mind governed by the flesh is death, but the mind governed by the Spirit is life and peace.", reference: "Romans 8:6" },
  { verse: "And we know that in all things God works for the good of those who love him.", reference: "Romans 8:28" },
  { verse: "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers.", reference: "Romans 8:38" },
  { verse: "Neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God.", reference: "Romans 8:39" },
  { verse: "How, then, can they call on the one they have not believed in? And how can they believe in the one of whom they have not heard?", reference: "Romans 10:14" },
  { verse: "Consequently, faith comes from hearing the message, and the message is heard through the word about Christ.", reference: "Romans 10:17" },
  { verse: "For from him and through him and for him are all things. To him be the glory forever! Amen.", reference: "Romans 11:36" },
  { verse: "Do not be overcome by evil, but overcome evil with good.", reference: "Romans 12:21" },
  { verse: "Let no debt remain outstanding, except the continuing debt to love one another.", reference: "Romans 13:8" },
  { verse: "The night is nearly over; the day is almost here. So let us put aside the deeds of darkness and put on the armor of light.", reference: "Romans 13:12" },
  { verse: "For the kingdom of God is not a matter of eating and drinking, but of righteousness, peace and joy in the Holy Spirit.", reference: "Romans 14:17" },
  { verse: "May the God who gives endurance and encouragement give you the same attitude of mind toward each other that Christ Jesus had.", reference: "Romans 15:5" },
  { verse: "The God of peace will soon crush Satan under your feet. The grace of our Lord Jesus be with you.", reference: "Romans 16:20" },
  { verse: "For the message of the cross is foolishness to those who are perishing, but to us who are being saved it is the power of God.", reference: "1 Corinthians 1:18" },
  { verse: "But God chose the foolish things of the world to shame the wise.", reference: "1 Corinthians 1:27" },
  { verse: "Do you not know that your bodies are temples of the Holy Spirit, who is in you, whom you have received from God?", reference: "1 Corinthians 6:19" },
  { verse: "So whether you eat or drink or whatever you do, do it all for the glory of God.", reference: "1 Corinthians 10:31" },
  { verse: "For whenever you eat this bread and drink this cup, you proclaim the Lord's death until he comes.", reference: "1 Corinthians 11:26" },
  { verse: "There are different kinds of gifts, but the same Spirit distributes them.", reference: "1 Corinthians 12:4" },
  { verse: "Just as a body, though one, has many parts, but all its many parts form one body, so it is with Christ.", reference: "1 Corinthians 12:12" },
  { verse: "If I speak in the tongues of men or of angels, but do not have love, I am only a resounding gong.", reference: "1 Corinthians 13:1" },
  { verse: "It always protects, always trusts, always hopes, always perseveres. Love never fails.", reference: "1 Corinthians 13:7-8" },
  { verse: "When I was a child, I talked like a child, I thought like a child, I reasoned like a child.", reference: "1 Corinthians 13:11" },
  { verse: "For now we see only a reflection as in a mirror; then we shall see face to face.", reference: "1 Corinthians 13:12" },
  { verse: "Follow the way of love and eagerly desire gifts of the Spirit.", reference: "1 Corinthians 14:1" },
  { verse: "But thanks be to God! He gives us the victory through our Lord Jesus Christ.", reference: "1 Corinthians 15:57" },
  { verse: "On the first day of every week, each one of you should set aside a sum of money in keeping with your income.", reference: "1 Corinthians 16:2" },
  { verse: "Praise be to the God and Father of our Lord Jesus Christ, who has blessed us in the heavenly realms with every spiritual blessing in Christ.", reference: "Ephesians 1:3" },
  { verse: "In him we have redemption through his blood, the forgiveness of sins.", reference: "Ephesians 1:7" },
  { verse: "For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God.", reference: "Ephesians 2:8" },
  { verse: "For he himself is our peace, who has made the two groups one.", reference: "Ephesians 2:14" },
  { verse: "Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.", reference: "Ephesians 3:20" },
  { verse: "There is one body and one Spirit, just as you were called to one hope when you were called.", reference: "Ephesians 4:4" },
  { verse: "Instead, speaking the truth in love, we will grow to become in every respect the mature body of him who is the head.", reference: "Ephesians 4:15" },
  { verse: "Do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up.", reference: "Ephesians 4:29" },
  { verse: "And do not grieve the Holy Spirit of God, with whom you were sealed for the day of redemption.", reference: "Ephesians 4:30" },
  { verse: "Speak to one another with psalms, hymns, and songs from the Spirit. Sing and make music from your heart to the Lord.", reference: "Ephesians 5:19" },
  { verse: "For our struggle is not against flesh and blood, but against the rulers, against the authorities.", reference: "Ephesians 6:12" },
  { verse: "Therefore put on the full armor of God, so that when the day of evil comes, you may be able to stand your ground.", reference: "Ephesians 6:13" },
  { verse: "Stand firm then, with the belt of truth buckled around your waist, with the breastplate of righteousness in place.", reference: "Ephesians 6:14" },
  { verse: "Take the helmet of salvation and the sword of the Spirit, which is the word of God.", reference: "Ephesians 6:17" },
  { verse: "For to me, to live is Christ and to die is gain.", reference: "Philippians 1:21" },
  { verse: "For it has been granted to you on behalf of Christ not only to believe in him, but also to suffer for him.", reference: "Philippians 1:29" },
  { verse: "Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves.", reference: "Philippians 2:3" },
  { verse: "Therefore God exalted him to the highest place and gave him the name that is above every name.", reference: "Philippians 2:9" },
  { verse: "That at the name of Jesus every knee should bow, in heaven and on earth and under the earth.", reference: "Philippians 2:10" },
  { verse: "Continue to work out your salvation with fear and trembling.", reference: "Philippians 2:12" },
  { verse: "For it is God who works in you to will and to act in order to fulfill his good purpose.", reference: "Philippians 2:13" },
  { verse: "Do everything without grumbling or arguing.", reference: "Philippians 2:14" },
  { verse: "But whatever were gains to me I now consider loss for the sake of Christ.", reference: "Philippians 3:7" },
  { verse: "I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.", reference: "Philippians 3:14" },
  { verse: "But our citizenship is in heaven. And we eagerly await a Savior from there, the Lord Jesus Christ.", reference: "Philippians 3:20" },
  { verse: "Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things.", reference: "Philippians 4:8" },
  { verse: "I have learned the secret of being content in any and every situation, whether well fed or hungry.", reference: "Philippians 4:12" },
  { verse: "And my God will meet all your needs according to the riches of his glory in Christ Jesus.", reference: "Philippians 4:19" },
  { verse: "The Son is the image of the invisible God, the firstborn over all creation.", reference: "Colossians 1:15" },
  { verse: "For God was pleased to have all his fullness dwell in him, and through him to reconcile to himself all things.", reference: "Colossians 1:19-20" },
  { verse: "So then, just as you received Christ Jesus as Lord, continue to live your lives in him.", reference: "Colossians 2:6" },
  { verse: "See to it that no one takes you captive through hollow and deceptive philosophy.", reference: "Colossians 2:8" },
  { verse: "Since, then, you have been raised with Christ, set your hearts on things above.", reference: "Colossians 3:1" },
  { verse: "Put to death, therefore, whatever belongs to your earthly nature.", reference: "Colossians 3:5" },
  { verse: "And over all these virtues put on love, which binds them all together in perfect unity.", reference: "Colossians 3:14" },
  { verse: "Wives, submit yourselves to your husbands, as is fitting in the Lord.", reference: "Colossians 3:18" },
  { verse: "For the Lord himself will come down from heaven, with a loud command.", reference: "1 Thessalonians 4:16" },
  { verse: "Therefore encourage one another and build each other up, just as in fact you are doing.", reference: "1 Thessalonians 5:11" },
  { verse: "Make sure that nobody pays back wrong for wrong, but always strive to do what is good for each other and for everyone else.", reference: "1 Thessalonians 5:15" },
  { verse: "Test all things; hold fast what is good.", reference: "1 Thessalonians 5:21" },
  { verse: "With this in mind, we constantly pray for you, that our God may make you worthy of his calling.", reference: "2 Thessalonians 1:11" },
  { verse: "The one who sows to please their flesh, from the flesh will reap destruction.", reference: "Galatians 6:8" },
  { verse: "Here is a trustworthy saying: If we died with him, we will also live with him.", reference: "2 Timothy 2:11" },
  { verse: "Flee the evil desires of youth and pursue righteousness, faith, love and peace.", reference: "2 Timothy 2:22" },
  { verse: "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.", reference: "2 Timothy 3:16" },
  { verse: "Preach the word; be prepared in season and out of season.", reference: "2 Timothy 4:2" },
  { verse: "For the grace of God has appeared that offers salvation to all people.", reference: "Titus 2:11" },
  { verse: "Let us then approach God's throne of grace with confidence.", reference: "Hebrews 4:16" },
  { verse: "For we do not have a high priest who is unable to empathize with our weaknesses.", reference: "Hebrews 4:15" },
  { verse: "The Son is the radiance of God's glory and the exact representation of his being.", reference: "Hebrews 1:3" },
  { verse: "Let us hold unswervingly to the hope we profess, for he who promised is faithful.", reference: "Hebrews 10:23" },
  { verse: "And let us consider how we may spur one another on toward love and good deeds.", reference: "Hebrews 10:24" },
  { verse: "Let us not give up meeting together, as some are in the habit of doing.", reference: "Hebrews 10:25" },
  { verse: "Now faith is confidence in what we hope for and assurance about what we do not see.", reference: "Hebrews 11:1" },
  { verse: "Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders.", reference: "Hebrews 12:1" },
  { verse: "Let us run with perseverance the race marked out for us, fixing our eyes on Jesus.", reference: "Hebrews 12:1-2" },
  { verse: "No discipline seems pleasant at the time, but painful. Later on, however, it produces a harvest of righteousness and peace.", reference: "Hebrews 12:11" },
  { verse: "Keep your lives free from the love of money and be content with what you have.", reference: "Hebrews 13:5" },
  { verse: "Jesus Christ is the same yesterday and today and forever.", reference: "Hebrews 13:8" },
  { verse: "Every good and perfect gift is from above, coming down from the Father of the heavenly lights.", reference: "James 1:17" },
  { verse: "Do not merely listen to the word, and so deceive yourselves. Do what it says.", reference: "James 1:22" },
  { verse: "But someone will say, 'You have faith; I have deeds.' Show me your faith without deeds, and I will show you my faith by my deeds.", reference: "James 2:18" },
  { verse: "As the body without the spirit is dead, so faith without deeds is dead.", reference: "James 2:26" },
  { verse: "Likewise, the tongue is a small part of the body, but it makes great boasts.", reference: "James 3:5" },
  { verse: "But the wisdom that comes from heaven is first of all pure; then peace-loving, considerate, submissive, full of mercy and good fruit.", reference: "James 3:17" },
  { verse: "Peacemakers who sow in peace reap a harvest of righteousness.", reference: "James 3:18" },
  { verse: "You do not have because you do not ask God.", reference: "James 4:2" },
  { verse: "God opposes the proud but shows favor to the humble.", reference: "James 4:6" },
  { verse: "Therefore confess your sins to each other and pray for each other so that you may be healed.", reference: "James 5:16" },
  { verse: "Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope.", reference: "1 Peter 1:3" },
  { verse: "For you have been born again, not of perishable seed, but of imperishable, through the living and enduring word of God.", reference: "1 Peter 1:23" },
  { verse: "Like newborn babies, crave pure spiritual milk, so that by it you may grow up in your salvation.", reference: "1 Peter 2:2" },
  { verse: "But you are a chosen people, a royal priesthood, a holy nation, God's special possession.", reference: "1 Peter 2:9" },
  { verse: "Live such good lives among the pagans that, though they accuse you of doing wrong, they may see your good deeds and glorify God.", reference: "1 Peter 2:12" },
  { verse: "For it is better, if it is God's will, to suffer for doing good than for doing evil.", reference: "1 Peter 3:17" },
  { verse: "But in your hearts revere Christ as Lord. Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have.", reference: "1 Peter 3:15" },
  { verse: "The end of all things is near. Therefore be alert and of sober mind so that you may pray.", reference: "1 Peter 4:7" },
  { verse: "Above all, love each other deeply, because love covers over a multitude of sins.", reference: "1 Peter 4:8" },
  { verse: "Offer hospitality to one another without grumbling.", reference: "1 Peter 4:9" },
  { verse: "Each of you should use whatever gift you have received to serve others, as faithful stewards of God's grace in its various forms.", reference: "1 Peter 4:10" },
  { verse: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
  { verse: "Be alert and of sober mind. Your enemy the devil prowls around like a roaring lion looking for someone to devour.", reference: "1 Peter 5:8" },
  { verse: "His divine power has given us everything we need for a godly life.", reference: "2 Peter 1:3" },
  { verse: "For this very reason, make every effort to add to your faith goodness; and to goodness, knowledge.", reference: "2 Peter 1:5" },
  { verse: "The Lord is not slow in keeping his promise, as some understand slowness. Instead he is patient with you.", reference: "2 Peter 3:9" },
  { verse: "But grow in the grace and knowledge of our Lord and Savior Jesus Christ.", reference: "2 Peter 3:18" },
  { verse: "If we claim to be without sin, we deceive ourselves and the truth is not in us.", reference: "1 John 1:8" },
  { verse: "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.", reference: "1 John 1:9" },
  { verse: "My dear children, I write this to you so that you will not sin. But if anybody does sin, we have an advocate with the Father.", reference: "1 John 2:1" },
  { verse: "Do not love the world or anything in the world. If anyone loves the world, love for the Father is not in them.", reference: "1 John 2:15" },
  { verse: "See what great love the Father has lavished on us, that we should be called children of God!", reference: "1 John 3:1" },
  { verse: "This is how we know what love is: Jesus Christ laid down his life for us.", reference: "1 John 3:16" },
  { verse: "Dear children, let us not love with words or speech but with actions and in truth.", reference: "1 John 3:18" },
  { verse: "This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us.", reference: "1 John 5:14" },
  { verse: "I have no greater joy than to hear that my children are walking in the truth.", reference: "3 John 1:4" },
  { verse: "But you, dear friends, by building yourselves up in your most holy faith and praying in the Holy Spirit.", reference: "Jude 1:20" },
  { verse: "To him who is able to keep you from stumbling and to present you before his glorious presence without fault.", reference: "Jude 1:24" },
  { verse: "I am the Alpha and the Omega, who is, and who was, and who is to come, the Almighty.", reference: "Revelation 1:8" },
  { verse: "Do not be afraid. I am the First and the Last.", reference: "Revelation 1:17" },
  { verse: "Yet I hold this against you: You have forsaken the love you had at first.", reference: "Revelation 2:4" },
  { verse: "Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in.", reference: "Revelation 3:20" },
  { verse: "You are worthy, our Lord and God, to receive glory and honor and power.", reference: "Revelation 4:11" },
  { verse: "And they sang a new song, saying: 'You are worthy to take the scroll and to open its seals.'", reference: "Revelation 5:9" },
  { verse: "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain.", reference: "Revelation 21:4" },
  { verse: "He who was seated on the throne said, 'I am making everything new!'", reference: "Revelation 21:5" },
  { verse: "Behold, I am coming soon! Blessed is the one who keeps the words of the prophecy written in this scroll.", reference: "Revelation 22:7" },
  { verse: "Behold, I am coming soon! My reward is with me, and I will give to each person according to what they have done.", reference: "Revelation 22:12" },
];

export function getDailyScripture(): Scripture {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000);
  return dailyScriptures[dayOfYear % dailyScriptures.length];
}
